# Kaggle submission notebook

In [1]:
import pandas as pd

df = pd.read_csv('../data/test.csv')
df.head()

,id,sleep_duration,heart_rate,bmi,calorie_expenditure,step_count,exercise_duration,water_intake,diet_type,stress_level,sleep_quality,physical_activity_level,smoking_alcohol,gender
0,690088,5.35,64.9,23.48,2745.0,14167.0,59.5,1.86,veg,high,poor,active,occasional,male
1,690089,NaN,83.1,22.42,1773.0,6801.0,24.5,2.40,balanced,high,poor,sedentary,yes,other
2,690090,6.68,59.7,24.14,3040.0,13250.0,48.5,2.76,balanced,medium,poor,active,no,NaN
3,690091,7.13,78.5,26.26,2494.0,6331.0,56.9,2.34,veg,low,good,moderate,yes,other
4,690092,5.49,77.7,23.29,1828.0,13894.0,39.4,2.45,veg,high,average,active,occasional,other

## Create dummy submission for workflow testing

In [2]:
submission_df = pd.DataFrame({
    'id': df['id'],
    'health_condition': ['at-risk'] * len(df)
})

submission_df.head()

       id health_condition
0  690088          at-risk
1  690089          at-risk
2  690090          at-risk
3  690091          at-risk
4  690092          at-risk

In [3]:
submission_df.to_csv('../data/submission.csv', index=False)